### ISSUE TITLE
Can't get stderr if script exits with non-zero exit code

### ISSUE THREAD

**Issue by JohnRusk** [Azure/custom-script-extension-linux#100]
I have looked at all of the following:
- /var/log/azure/custom-script/handler.log
- /var/log/waagent.log
-  /var/log/azure/Microsoft.Azure.Extensions.CustomScript/2.0.3/CommandExecution.log
- and, from a separate template: reference('Microsoft.Compute/virtualMachines/my-vm/extensions/installation-script', '2016-04-30-preview').instanceView

But none of them show the contents of stderr when there has been a failure.  Is there way to see stderr in such cases? If not, could one be added?

**Comment by boumenot** [comment]
There is a [test](https://github.com/Azure/custom-script-extension-linux/blob/master/integration-test/test/handler-commands.bats#L48-L65) to assert this behavior, but perhaps it is broken.

Can you please provide a repro, and information about the VM environment you're using.

**Comment by JohnRusk** [comment]
Hi. I just didn't look in the right place, sorry!
