### ISSUE TITLE
What is the desired behaviour when reprovisioning?

### ISSUE THREAD

**Issue by JohnRusk** [Azure/custom-script-extension-linux#101]
If I deallocate then reallocate a Windows VM, then the custom script re-runs.  But using this Linux extension, I'm not observing the same behavior. Is it supposed to re-run when the VM is re-allocated?

**Comment by boumenot** [comment]
This is better directed at the [Linux Guest Agent repo](https://github.com/Azure/WALinuxAgent). Please open an issue.  If there is a discrepancy between the way the two GAs work it needs to be understood and resolved.
