### ISSUE TITLE
Script not re-running on timestamp update for VM Scale Sets deployment via ARM

### ISSUE THREAD

**Issue by deagrawa-azure** [Azure/custom-script-extension-linux#103]
[CustomScriptLogs.zip](https://github.com/Azure/custom-script-extension-linux/files/1295677/CustomScriptLogs.zip)

Please find attached the logs for the re-running of CustomScript Extension with timestamp update on Virtual Machine Scale Sets deployment via ARM template. I have tried the re-run on timestamp update on VM instance. That works. As per the logs for run on VM instances which are part of VM scale sets, the re-run of Custom Script Extension is not able to figure out that the new extension profile is an updated one with different timestamp value.

I have attached following files
- /var/log/azure/custom-script/handler.log
- /var/log/waagent.log
- initial run Extension profile and updated one

**Comment by agolomoodysaada** [comment]
Experiencing the same issue here when changing the command to execute.

**Comment by agolomoodysaada** [comment]
I found a workaround.
I was able to run

```sh
az vmss update-instances --instance-ids '*' \
                         -n <vmss-name> \
                         -g <resource-group>
```

before update the custom-script extension. 
Upgrading the VMSS instances through the portal works as well.

**Comment by deagrawa-azure** [comment]
I got an answer from Microsoft and the answer is that 'upgradePolicy' needs to be set to 'Automatic' for VMSS and then, Custom Script would be re-run on re-deploy with updated timestamp value.
