### ISSUE TITLE
Changing property 'type' is not allowed.

### ISSUE THREAD

**Issue by throrin19** [Azure/custom-script-extension-linux#105]
Hi,
I try to change an existing VMScaleset script with the az client but I have an unexpected error with no explication in documentation, issue, ...

If I launch the list command : `az vmss extension list --resource-group <group> --vmss-name <scaleset>`, I have this result :

```
[
  {
    "autoUpgradeMinorVersion": false,
    "id": null,
    "name": "Rancher_agents",
    "protectedSettings": null,
    "provisioningState": null,
    "publisher": "Microsoft.Azure.Extensions",
    "settings": {
      "commandToExecute": "<my command>",
      "fileUris": [
         "<my file uri>"
      ]
    },
    "type": "CustomScript",
    "typeHandlerVersion": "2.0"
  }
]
```

Then, I try to update this with this command :

```
az vmss extension set --name Rancher_agents --publisher Microsoft.Azure.Extensions --version 2.0 --resource-group <group> --vmss-name <scaleset> --settings ./extension.json
```

And this is the `extension.json` content :

```
{
    "commandToExecute": "<my command>",
    "fileUris" : [
        "<my new file uri"
    ]
}
```

But, when I launch the script, I have this error :

```
Changing property 'type' is not allowed.
```

How to fix that ?

Thanks

**Comment by boumenot** [comment]
Sorry for the late response.  I am not familiar with VMSS, but the error message appears to indicate that extension type is incorrect. An extension has three parts.

 1. Namespace - Microsoft.Azure.Extensions
 1. Type (or Name) - CustomScript
 1. Version - 2.0

The error message appears to indicate the type is wrong in some way.  It looks like you set the name to Rancher_agents, which is incorrect.  It should be CustomScript. My guess is you meant Ranger_agents for the **--vmss-name** parameter.

```sh
az vmss extension set --vmss-name Rancher_agents --name CustomScript --publisher Microsoft.Azure.Extensions --version 2.0 --resource-group <group> --vmss-name <scaleset> --settings ./extension.json
```

**Comment by throrin19** [comment]
@boumenot I agree with that. But actually, it is not possible to set the type. 

After many tests, the type is the exactly same as the name field. But, in real case, you want name your extensions to know them directly and set the type distinctly.
