### ISSUE TITLE
Getting script output from Azure SM powershell

### ISSUE THREAD

**Issue by jefshe** [Azure/custom-script-extension-linux#112]
I'm executing a script with a large output using this extension on a classic VM.

Is there a way to get the output of the script from powershell? I tried Get-AzureVM but that only gives me the status and a simple message. I've also tried Get-AzureVMDiagnosticsExtension but this returns nothing.

I've tried uploading the output log to blob storage within the script itself but if the script fails there is no way to get the output.

**Comment by boumenot** [comment]
Do you see anything in portal?  This would help clarify if it any output exists or not.

If the script fails stdout/stderr are not reported. This is a bug.  There is a fix #111 to correct this issue.

**Comment by jefshe** [comment]
Oh yep I can see the output on the portal when the script succeeds, I think the output is not being generated only when the script fails. 
Since there is a fix for that i'll close this ticket
