### ISSUE TITLE
CustomScript is Re-executing Previously Executed Scripts

### ISSUE THREAD

**Issue by boumenot** [Azure/custom-script-extension-linux#117]
v2.0.5 is re-executing previously executed scripts.

**Comment by boumenot** [comment]
v2.0.4 had a bug where uninstall was called, and the state directory was deleted. The extension was configured to not run install on upgrade, so the directory was deleted on uninstall but not recreated after upgrade.  The directory was not created because install was not called. This meant customers were unable to execute scripts.  This bug has existed since the beginning.

v2.0.5 fixed this issue, but caused previously executed scripts to be re-executed.  The state directory is deleted on uninstall, and properly re-created on install  The state directory contains the last executed sequence, which would indicate to the extension what version was last executed. Because the directory was deleted and re-created the sequence number was lost and the script was re-run.  This is bad.

The fix is to not re-invent a scratch directory.  The agent has explicit support for tracking the last executed sequence, and it expects extensions to store this information in a file called mrseq. The file should be located in /var/lib/waagent/Microsoft.Azure.Extensions__CustomScript__2.0.5, where 2.0.5 represents the current version.

**Comment by Elexy** [comment]
@boumenot Could this have caused the VM to reboot? My VMs ***all*** got rebooted after the upgrade.

**Comment by boumenot** [comment]
Sorry.  The upgrade process does not reboot, but it did re-run previously run scripts.  Did your script have a reboot command in it?

**Comment by Elexy** [comment]
@boumenot there is no script:
{
  "autoUpgradeMinorVersion": true,
  "forceUpdateTag": null,
  "id": "/subscriptions/0f268b87-6f3f-48b1-a0e1-374eb36f57ae/resourceGroups/dgs-uat/providers/Microsoft.Compute/virtualMachines/k8s-agent-2573B5B1-3/extensions/cse3",
  "instanceView": null,
  "location": "westeurope",
  "name": "cse3",
  "protectedSettings": null,
  "provisioningState": "Succeeded",
  "publisher": "Microsoft.Azure.Extensions",
  "resourceGroup": "dgs-uat",
  "settings": {},
  "tags": null,
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "typeHandlerVersion": "2.0",
  "virtualMachineExtensionType": "CustomScript"
}

**Comment by boumenot** [comment]
Is that the response/status, or is that the configuration you pushed down?

CustomScript has no code to reboot a VM.  Please open a new issue with logs, and I can dig into this more.

**Comment by boumenot** [comment]
v2.0.6 has been released to address this issue.
