### ISSUE TITLE
VMSS add ssh key stalls at "- Running" forever

### ISSUE THREAD

**Issue by agolomoodysaada** [Azure/custom-script-extension-linux#124]
After running
```sh
az vmss extension set \
  --vmss-name myvmss \
  -g myresourcegroup \
  -n VMAccessForLinux \
  --publisher Microsoft.OSTCExtensions \
  --version 1.4 \
  --protected-settings "{\"username\":\"myuser\", \"ssh_key\":\"$(cat ~/.ssh/mykey.pub)\"}"
```
The command stalls at `- Running` indefinitely without ever returning. I was able to reproduce this on several VMSSs.

P.S. I do not have access to the VMs in the vmss so I cannot retrieve contents of the files:

- /var/log/azure/custom-script/handler.log
- /var/log/waagent.log

This used to work just fine. Any idea why the custom script doesn't work anymore?

**Comment by boumenot** [comment]
This is the repository for Microsoft.Azure.Extensions.CustomScript.  You opened a bug for Microsoft.OSTCExtensions.VMAccessForLinux, which is covered by Azure/azure-linux-extensions.

If you do not have logs it will be difficult to determine why it failed.  VMAccessForLinux has not changed in >6 months.  Why do you think this an issue with VMAccessForLinux?
