### ISSUE TITLE
Deprovision fails on Red Hat 7.2

### ISSUE THREAD

**Issue by grwann** [Azure/custom-script-extension-linux#125]
Hello,

We have a customer running into issues running deprovision on the Red Hat 7.2 linux flavor.  It is odd because deprovision is working on Red Hat 6.9, 7.4, and 6.7.  Also, the customer said these issues started happening around December 1.

It's odd because I can eventually get deprovision to work, but only if I run these steps in this order: run deprovision and wait for it to fail, run a custom script extension that essentially does nothing, and rerun deprovision again.

I read up on these threads https://github.com/Azure/custom-script-extension-linux/issues/94, https://github.com/Azure/custom-script-extension-linux/issues/84 of customers with similar issues, and it was explained that upgrading to a guest agent version 2.1+ and CSE version 2.0.6 would fix these problems.  However, the vms we use have agent version 2.2.18 and CSE version 2.0.6.

I did run rm -rf /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript*/ on the vm and deprovision worked after, but our customers expect to run automations.

At the moment I am having issues logging into my red hat machine but the output of my /var/log/waagent.log from a failed attempt yesterday looked like the customer log in git issue #94:

```
Not writing a placeholder status file, already exists: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/status/0.status
+ nohup /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/bin/custom-script-extension enable
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=start
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=pre-check
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="checking for state migration"
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="no old state found to migrate"
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="comparing seqnum" path=/var/lib/waagent/custom-script/seqnum
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=exit message="this script configuration is already processed, will not run again"
```

When I am able to log in again I will sent gists of /var/log/azure/custom-script/handler.log and /var/log/waagent.log

Thank you very much

**Comment by boumenot** [comment]
Are you trying to run deprovision from CustomScript?  If so, this is not supported.  In this scenario, you are deleting the directory you're executing in.

**Comment by grwann** [comment]
Yes, we are running deprovision from CustomScript.

Do you mean that running deprovision from CustomScript is not supported, or you wouldn't recommend running rm -rf /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript*/?

**Comment by boumenot** [comment]
Yes, I mean running it from CustomScript is not supported.  You are deleting all of CustomScript's data while CustomScript is running.  This is not a  good idea.

**Comment by grwann** [comment]
Thank you.  We are considering other mechanisms of running deprovision, in the meantime we've found a workaround for this issue.

**Comment by kcheick** [comment]
@grwann can you please share your workaround to run the deprovision in the custom script? We are running into the same issue in our service.

**Comment by grwann** [comment]
@kcheick the workaround in our case was to edit the script we used to run deprovision to remove updating yum.  The update caused Red Hat to upgrade to a newer version, which caused issues with the deprovision.
