### ISSUE TITLE
Fails to install software that need sudo even though azure runs it as root

### ISSUE THREAD

**Issue by vairamsvsjdo** [Azure/custom-script-extension-linux#126]
ENV Ubuntu 17.10 Canonical Template available in azure.

Fails to install software that need sudo even though azure runs it as root

example script for script.sh
``` bash
time  apt-get -y update
time  apt install -y python3-pip 
```
The above script fails to run unless other sudo sh script.sh is the command in custom extension to execute

**Comment by boumenot** [comment]
You need to provide logs for progress to make on this issue.  Please see the issue template (displayed when you opened the bug) for the list of logs to include.

**Comment by johanburati** [comment]
I was not able to replicate on `Canonical:UbuntuServer:17.10:latest` image , both commands worked fine, `python3-pip` package and dependencies got installed.

`/var/lib/waagent/custom-script/download/0/script.sh`
```
#/bin/sh
time  apt-get -y update
time  apt install -y python3-pip 
```

**Comment by boumenot** [comment]
Thank you for trying to reproduce.  I am closing this issue for now.  Please re-open if you can provide the necessary logs.
