### ISSUE TITLE
cannot run same bash script twice

### ISSUE THREAD

**Issue by saimsh** [Azure/custom-script-extension-linux#129]
If you are encountering issues, please take a look at the following log files
on your virtual machine and provide their contents in the issue description:

- /var/log/azure/custom-script/handler.log
- /var/log/waagent.log

====

hi team,
i have a customer who is experiencing issues with running the same script twice. I tested this in a centos7.3 environment  using both az cli (cloudshell) and azure xplat cli and the issue can be easily replicated for Custom script version 2.0.6

reproduction steps:
- enable custom script extension to perform any operation ( useradd, file creation, package installation)
- when checking in the linux client- custom script execution is successful as expected ( from handler.log, command execution.log and waagent.log)
- Run the same command again with minor tweak in the script ( or simply uninstall the previously installed package manually)
- nothing is recorded within (waagent.log/handler.log/Commandexecutionlog). also , the script is not downloaded  within (/var/lib/waagent/custom-script/download

saim@Azure:~$ az vm extension set --resource-group centos73arm --vm-name centos73 --name customScript --publisher Microsoft.Azure.Extensions --version 2.0 --settings ./script1-config.json
{
  "additionalProperties": {},
  "autoUpgradeMinorVersion": true,
  "forceUpdateTag": null,
  "id": "/subscriptions/42e99167-6059-4fe7-a2f3-f0ae430386d3/resourceGroups/centos73arm/providers/Microsoft.Compute/virtualMachines/centos73/extensions/CustomScript",
  "instanceView": null,
  "location": "westeurope",
  "name": "CustomScript",
  "protectedSettings": null,
  "provisioningState": "Succeeded",
  "publisher": "Microsoft.Azure.extensions",
  "resourceGroup": "centos73arm",
  "settings": {
    "commandToExecute": "./passwordauth.sh",
    "fileUris": [
      "https://mycustomscript.blob.core.windows.net/saimcont/passwordauth.sh"
    ]
  },
  "tags": null,
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "typeHandlerVersion": "2.0",
  "virtualMachineExtensionType": "CustomScript"
}
saim@Azure:~$ date
Tue Apr  3 20:30:58 UTC 2018

handler log:
Writing a placeholder status file indicating progress before forking: /var/lib/waagent/Microsoft.Azure.extensions.CustomScript-2.0.6/status/5.status
+ nohup /var/lib/waagent/Microsoft.Azure.extensions.CustomScript-2.0.6/bin/custom-script-extension enable
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event=start
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event=pre-check
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="comparing seqnum" path=mrseq
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="seqnum saved" path=mrseq
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="reading configuration"
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="read configuration"
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="validating json schema"
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="json schema valid"
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="parsing configuration json"
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="parsed configuration json"
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="validating configuration logically"
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="validated configuration"
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="creating output directory" path=/var/lib/waagent/custom-script/download/5
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="created output directory"
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 files=1
time=2018-04-03T19:49:42Z version=v2.0.6/git@1008306-clean operation=enable seq=5 file=0 event="download start"
time=2018-04-03T19:49:43Z version=v2.0.6/git@1008306-clean operation=enable seq=5 file=0 event="download complete" output=/var/lib/waagent/custom-script/download/5
time=2018-04-03T19:49:43Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="executing command" output=/var/lib/waagent/custom-script/download/5
time=2018-04-03T19:49:43Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="executing public commandToExecute" output=/var/lib/waagent/custom-script/download/5
time=2018-04-03T19:49:43Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event="executed command" output=/var/lib/waagent/custom-script/download/5
time=2018-04-03T19:49:43Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event=enabled
time=2018-04-03T19:49:43Z version=v2.0.6/git@1008306-clean operation=enable seq=5 event=end
[root@centos73 custom-script]#

as you can see nothing is recorded for the time stamp around 20:30 pm UTC

- is this by design ?
- the script name itself needs to change for the execution to work again ( changing the public json file name, script contents does not help)

thanks
saim

**Comment by boumenot** [comment]
This is by design.  This is documented in the README.

**Comment by saimsh** [comment]
hi christopher, 
thank you for the prompt response. Just tested multiple reruns with timestamps under public json. things are running as expected. 
cheers!! :-)
saim
