### ISSUE TITLE
Updating scripts mssing 

### ISSUE THREAD

**Issue by cloudmelon** [Azure/custom-script-extension-linux#130]
If you are encountering issues, please take a look at the following log files
on your virtual machine and provide their contents in the issue description:

- /var/log/azure/custom-script/handler.log
- /var/log/waagent.log

Hi, I deployed the VMSS ( linux-based VMs ) successfully with custom script extension in each VM at the 1st time, now I meet another problem is to update the scripts in a custom script. I knew I can redeploy the whole template with script v2 but is any way to update only the custom script part existing? 

As I resumed to update VMSS with extension 
-  To upgrade OS image ( with VMSS upgrade policy : automatic ,  manuel and rolling ) 
- To update the version of extension 
- is any way to update only the custom script in extension  existing  ? 

Thank you :)

**Comment by boumenot** [comment]
Sorry, but I cannot answer these questions.  My knowledge is about the extension, not about VMSS.

What do you mean by update the version of the extension?  CustomScript is currently at v2.0.6, and has been for a few months.  I would not expect you to control this version.

When you say update the script, do you mean re-run the extension with a new version of the script?  I think the answer is just to deploy the extension again with a different setting.  The [timestamp](https://github.com/Azure/custom-script-extension-linux#1-extension-configuration) may also be relevant.

**Comment by cloudmelon** [comment]
Hi Christopher,

Thank you for your information, I mean re-run the extension with a new version of the script? I think I’ll try to redeploy the extension in VMSS with updated scripts. Have a great night :)

Melony QIN

**Comment by boumenot** [comment]
If the settings of the extension are identical, the script will not be re-run.  The *middle* layers will prevent the same settings from getting to CustomScript extension.  CustomScript will never see your command as a result.  You must change the settings in some way to force re-execution.  The recommended way to do this is to add a timestamp parameter to your settings, and increment timestamp whenever you want the script to re-execute.

```json
{
  "commandToExecute": "echo 'Hello World'",
  "timestamp": 0
}
```

Re-execute the same script.  Note that timestamp was changed to the value 1.

```json
{
  "commandToExecute": "echo 'Hello World'",
  "timestamp": 1
}
```

The middle layers determine something has changed by doing a string comparison of the previous settings with the current settings.  It should be a JSON comparison, but it's a string compare.

**Comment by cloudmelon** [comment]
Thank you Christopher, very clear explanation :)

PS. I did a test with Azure CLI which redeploy a custom scripts extension in VMSS this afternoon, results exactly as you said. It’s working well thank you!

Melony QIN

**Comment by boumenot** [comment]
Awesome!

I think this answers the questions I can answer, so I am closing. Ping me or re-open if you have more.

**Comment by cloudmelon** [comment]
Fingers crossed :)

Melony QIN
