### ISSUE TITLE
How to Write public IP on the time of Linux VM Building??

### ISSUE THREAD

**Issue by Anmolgan81** [Azure/custom-script-extension-linux#131]
Can anyone tell us how can we write public ip inside a Ubuntu 14.04.5 LTS, on the time of VM Creation.
Any steps on how to do this will be helpful.

**Comment by boumenot** [comment]
This repository is for CustomScript, and I do not see how this question is relevant.

**Comment by Anmolgan81** [comment]
Can you give me a solution for this or else tell me where should I post it in order to get a viable solution for this?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by boumenot** [comment]
Sorry, I do not have an answer for either.

**Comment by Anmolgan81** [comment]
Then this is no help to me


Regards,
[1512717838432_download.png]


Anmol Ganju | IFI Techsolutions
Mobile: +91-90-826-13399
Email: anmol.ganju@ifi.tech<mailto:anmol.ganju@ifi.tech>| http://ifi.tech<http://ifi.tech/>



________________________________
