### ISSUE TITLE
Question - Script property (Base64 + Dynamic parameters)

### ISSUE THREAD

**Issue by jorgecotillo** [Azure/custom-script-extension-linux#132]
What would be the option if I have the following:

1. VM that force-tunnel the outbound internet connectivity to a NVA (default route)
2. There is a extension that resides in a storage account (let's say that Service Endpoint is not an option because the file can actually resides in any location)

Now, I would like to download the file and pass dynamic parameters (say IP addresses).
Since there is no internet connection I thought on using "script" parameter and base64 +gzip my sh file, but now I am facing an issue that I am not sure how to pass my IP parameters.

Any help would be really appreciated.

**Comment by boumenot** [comment]
The script parameter does not currently take any parameters.  It is assumed to be self-encased.

Is the parameter really dynamic?  It sounds like you know the IP address, and you are injecting it as a parameter.  Are you able to inject it into your script?  Not a great solution, but it will unblock you.

Alternatively...

 1. We could teach custom script how to take parameters via a new option.
 1. We could allow the script parameter to be passed, and use the existing commandToExecute option. The script will have a well known name, such as script.sh, and you could construct your command line that way.

**Comment by boumenot** [comment]
Please re-open as appropriate.
