### ISSUE TITLE
az vm extension set --settings configuration issue

### ISSUE THREAD

**Issue by waynenus** [Azure/custom-script-extension-linux#136]
Hi Team,

Is the JSON no longer supported by the _--settings_ ?

PS C:\> az vm extension set  --resource-group CentOS  --vm-name CentOS75 --name customScript  --publisher Microsoft.Azure.Extensions --settings '{
>> "fileUris": ["https://raw.githubusercontent.com/gm12367/software_list/master/test.sh"],
>> "commandToExecute": "./test.sh"
>> }' --version 2.0
**Expecting property name enclosed in double quotes: line 1 column 2 (char 1)**

No entries in handler.log

**Comment by boumenot** [comment]
This is the repository for CustomScript, but your questions appears to be about the CLI.  Please re-open the issue there.

Having said that, I cannot imagine a world in which the CLI stopped accepting JSON.  This would break everybody.  I suspect there's either a syntax issue, or your shell is messing with your quotes.
