### ISSUE TITLE
How to get the script response?

### ISSUE THREAD

**Issue by dtissen** [Azure/custom-script-extension-linux#137]
Maybe I'm confused but how to get the response of the execution? customscripts are useless unless you can get the response, isn't it?

**Comment by boumenot** [comment]
I believe most people depend on a simple pass fail of the extension deployment.  If you want the stdout/stderr output of the extension you can get the instanceView of the VM.  You can access the instanceView using the API.  Please visit https://resources.azure.com and navigate to your VM to locate the instanceView.  This will give you an idea of the output that is available.

e.g.

```json
{
"extensions": [
    {
      "name": "CustomScript",
      "type": "Microsoft.Azure.Extensions.CustomScript",
      "typeHandlerVersion": "2.0.6",
      "statuses": [
        {
          "code": "ProvisioningState/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "message": "Enable succeeded: \n[stdout]\nstderr\nstdout\n\n[stderr]\n"
        }
      ]
    }
  ]
}
```

**Comment by dtissen** [comment]
Sorry, but does not solve the issue: If i need a synchronous answer to the customscript then it is not a good option to manually go to the vm ressource and open something.. 

Executing a command without the answer is like gambling. You dont know if it successful.

**Comment by boumenot** [comment]
I was using the web site to illustrate the output.  I was not suggesting it as an answer.  The answer is to make an API call to get the output.
