### ISSUE TITLE
Does the Azure RM Powershell support the custom-script-extension-linux ?

### ISSUE THREAD

**Issue by waynenus** [Azure/custom-script-extension-linux#138]
As title, I want to use Azure RM Powershell to run an custom script in the Linux VMs by custom-script-extension. I don;t find any reference regarding this, is it possible?

**Comment by boumenot** [comment]
Yes, please see the documentations for [Set-AzureRMVMExtension](https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmextension?view=azurermps-6.5.0).
