### ISSUE TITLE
customescriptextension and terraform provisioners are not working in Windows SQL server Machine

### ISSUE THREAD

**Issue by AvinashReddyVaka** [Azure/custom-script-extension-linux#140]
Hi guys,

i am trying to create a SSIS Windows VM, where i am spinning up a SQL sever VM and trying to automatically disable SQLServer, ReportServer  and Olap services on VM. I tried using provisioners and Custom script extension to disable them, but none of the ways are working.

Below is the sample script that i am using:

resource "azurerm_resource_group" "test" {
  name     = "acctestRG"
  location = "West US 2"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctvn"
  address_space       = ["10.0.0.0/16"]
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_subnet" "test" {
  name                 = "acctsub"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_network_name = "${azurerm_virtual_network.test.name}"
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "test" {
  name                = "acctni"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = "${azurerm_subnet.test.id}"
    private_ip_address_allocation = "dynamic"
  }
}

resource "azurerm_network_security_group" "test" {
  name                = "acceptanceTestSecurityGroup1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  security_rule {
    name                       = "test123"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_managed_disk" "test" {
  name                 = "datadisk_existing"
  location             = "${azurerm_resource_group.test.location}"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "1023"
}

resource "azurerm_virtual_machine" "test" {
  name                  = "acctvm"
  location              = "${azurerm_resource_group.test.location}"
  resource_group_name   = "${azurerm_resource_group.test.name}"
  network_interface_ids = ["${azurerm_network_interface.test.id}"]
  vm_size               = "Standard_B2s"

  # Uncomment this line to delete the OS disk automatically when deleting the VM
  # delete_os_disk_on_termination = true

  # Uncomment this line to delete the data disks automatically when deleting the VM
  # delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = "MicrosoftSQLServer"
    offer     = "SQL2012SP4-WS2012R2"
    sku       = "Standard"
    version   = "latest"
  }
  storage_os_disk {
    name              = "myosdisk1"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
  # Optional data disks
  storage_data_disk {
    name              = "datadisk_new"
    managed_disk_type = "Standard_LRS"
    create_option     = "Empty"
    lun               = 0
    disk_size_gb      = "1023"
  }
  storage_data_disk {
    name            = "${azurerm_managed_disk.test.name}"
    managed_disk_id = "${azurerm_managed_disk.test.id}"
    create_option   = "Attach"
    lun             = 1
    disk_size_gb    = "${azurerm_managed_disk.test.disk_size_gb}"
  }
  os_profile {
    computer_name  = "hostname"
    admin_username = "testadmin"
    admin_password = "Password1234!"
  }
  os_profile_windows_config {
    provision_vm_agent        = "true"
    enable_automatic_upgrades = "false"

    winrm {
      protocol        = "http"
      certificate_url = ""
    }
  }
  tags {
    environment = "staging"
  }
  provisioner "file" {
    source      = "C:/Users/avaka2/Desktop/Terraform_AVrc/Learn_vm/file/PSScript_RunBook_Automation_Run.txt"
    destination = "D:/filetest"

    connection {
      type     = "winrm"
      user     = "testadmin"
      password = "Password1234!"
    }
  }
}

/*resource "azurerm_virtual_machine_extension" "test" {
  name                 = "test"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  location             = "${azurerm_resource_group.test.location}"
  virtual_machine_name = "${azurerm_virtual_machine.test.name}"
  publisher            = "Microsoft.compute"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.2"

  settings = <<SETTINGS
    {
        "commandToExecute": "powershell.exe Set-Service MSSQLSERVER -startupType Disabled"
    }
SETTINGS

  depends_on = ["azurerm_virtual_machine.test"]
}*/

Any pointers on this??? Thank you in advance.

**Comment by boumenot** [comment]
This extension is for Linux, and is not applicable to Windows.  Sorry, but this is not something I can help you with.
