### ISSUE TITLE
Is there a way to restart the walinuxagent after the script ends, without breaking the deplyoment?

### ISSUE THREAD

**Issue by evertonmc** [Azure/custom-script-extension-linux#142]
I need to i.e. restart the agent after creating SwapPartitions
```
echo "Enabling Swap"
sed -i 's/ResourceDisk.EnableSwap=n/ResourceDisk.EnableSwap=y/g' /etc/waagent.conf
sed -i 's/ResourceDisk.Format=n/ResourceDisk.Format=y/g' /etc/waagent.conf
sed -i 's/ResourceDisk.SwapSizeMB=0/ResourceDisk.SwapSizeMB=8192/g' /etc/waagent.conf
echo "Restarting walinuxagent"
sudo service walinuxagent restart
```
but calling _service walinuxagent restart_ leaves the extension unattended and the deployment doesn't end

**Comment by boumenot** [comment]
My recommendation is to schedule the restart using the `at` command, or to use [Packer](http://packer.io), which is not beholden to the agent or extensions.

HTH
