### ISSUE TITLE
Make the stdout/err tail size configurable

### ISSUE THREAD

**Issue by stan-sz** [Azure/custom-script-extension-linux#152]
Currently the `maxTailLen` is constant to be `4 * 1024 // length of max stdout/stderr to be transmitted in .status file`. Can this be configurable via arm template? Possible a special value indicating that no tailing, but the whole stdout/err should be sent back.

**Comment by D1v38om83r** [comment]
No, It is not possible to configure it with ARM template. The status file is not meant to transmit large volumes of data.

If you are looking to debug the script on your VM, CSE on Linux writes the output of stdout and stderr files to the disk at 
/var/lib/waagent/custom-script/download/<n>/stdout
and
/var/lib/waagent/custom-script/download/<n>/stderr
