### ISSUE TITLE
[todo] add enableInternalDNSCheck optional setting 

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/custom-script-extension-linux#34]
`enableInternalDNSCheck` optional setting should be `false` by default and should reside in public settings section.

If configured, it should retry about 2 minutes until the command `host $(hostname)` command works (this makes sure the internal DNS is set up correctly). Even though the retries fail, we should keep going (that's what existing v1.5 does)

Why do people need this feature? Sometimes customers use CustomScriptExtension to run some startup scripts such as configuring an app that talks to a database in another machine in the VNET, and they refer to the other machine with its hostname. If Internal DNS is not ready, then their scripts resolving another machine in the same VNET will fail.

This feature should be obsolete when the networking team guarantees that IDNS will be fully functioning when the VM is powered on.

cc: @boumenot

**Comment by boumenot** [comment]
Ugh.  We should strive to maintain compatibility, but it seems like we over extended ourselves on this one.  It seems simple enough for a customer to implement themselves.

**Comment by ahmetalpbalkan** [comment]
@boumenot but this sounds like a guarantee the infra should be providing. we can always advise customers do have this in their scripts but it would be nice to offer this feature. I guess first we should figure out if this issue is fixed... I'm trying to get more context on the offline thread.

**Comment by boumenot** [comment]
Customers can do whatever they want with their VMs including not allowing them to connect to the public internet, or have an IP.

I look forward to the answer. 👍

**Comment by ahmetalpbalkan** [comment]
> Customers can do whatever they want with their VMs including not allowing them to connect to the public internet, or have an IP.

that's why I was suggesting this as a _disabled by default and can opt-in_ type of knob.

**Comment by boumenot** [comment]
Touche'

**Comment by ahmetalpbalkan** [comment]
So per offline threads and discussions. Findings:

1. This got added because some templates use `hostname` command to figure out their VM name (due to lack of metadata API). Azure Container Service was impacted by this in D14-size VMs very clearly.

2. Former extension author suggests _"this setting should be disabled by default"_ but in the old codebase [it is enabled by default](https://github.com/Azure/azure-linux-extensions/commit/f99252f49a7d6c9ce7ae0b4e26d2ba2ed449f585#diff-e96c2eba389f9c7af34868e4e987ecfeR272) effectively causing all Expressroute VMs and VMs with custom dns settings to fail.

3. Reportedly networking team fixed this in November 2015 but there has been reports of this occurring in December 2015 as well. 

Action here:

- use [this](https://github.com/anhowe/scratch/blob/master/reliableCustomScriptExtension/reliableCustomScript.json) template with D14 VMs (remove customscript section) and deploy bunch of VMs (set `enableInternalDNSCheck` to `false` in extension config) and see the DNS issue is still there.
    - if issue went away, no action
    - if issue is there, add the feature and make this key _optional_ and _disabled by default_.

**Comment by ahmetalpbalkan** [comment]
It appears like this issue has been fixed. I cannot reproduce this on D14 size VMs anymore by running a script via cloud-init. I tried it 20 times or so. The `host $(hostname)` works on the first try when cloud-init has started.

Env I used to reproduce (docker/machine with PR 3592 patched):

```
export AZURE_LOCATION=centralus
export AZURE_SIZE=Standard_D14
export AZURE_IMAGE=canonical:UbuntuServer:16.04.0-LTS:latest
export AZURE_CUSTOM_DATA_FILE=~/cloud-config.yaml

for i in `seq 0 20`; do
    echo "------------------> $i"
    R=$RANDOM;VM=t$R; RG=ahmetb-idns-$R;
    time AZURE_RESOURCE_GROUP=$RG ~/docker-machine create -d azure $VM && \
        docker-machine ssh $VM cat /var/log/cloud-init-output.log | grep HELLO -A 10
    timeout 60 azure group delete -q $RG &
done
```

cloud-config.yaml:

```yml
#cloud-config
runcmd:
 - ["/bin/bash", "-c", "echo HELLO; while true; do h=\"$(host $(hostname))\"; st=$?; echo \"[$(date)] --($st)--> $h\"; if [ \"$st\" -eq 0 ]; then exit; fi; sleep 0.1; done; echo DONE"]
```
