### ISSUE TITLE
All the scripts downloaded are executable

### ISSUE THREAD

**Issue by bingosummer** [Azure/custom-script-extension-linux#58]
Is it by design?
In 1.x version, only the entry script is executable.

**Comment by ahmetalpbalkan** [comment]
sorry for seeing this late. @bingosummer yes it is by design. We discussed it and found no harm in adding +x to all files downloaded. The v1.x etension's  logic of determining the entry script was very simply flawed: https://github.com/Azure/azure-linux-extensions/issues/200
