### ISSUE TITLE
Expose stdout/stderr of the script in status file (and on portal/resource explorer)

### ISSUE THREAD

**Issue by xpillons** [Azure/custom-script-extension-linux#67]
With the OSTCExtensions release, stdout and stderr were displayed into the status of the instance view of a VM. In my case the message is "Enable in progress" and displayStatus is "Transitioning" while the script is finished and well executed.

**Comment by ahmetalpbalkan** [comment]
@xpillons thanks for reporting. We omitted showing script output on the API/portal/resource explorer on the new version. However the "Transitioning" status should be going away once the script is finished.

Can you please take a screenshot from the portal and grab the files in `/var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.1/status/*` and attach them here for troubleshooting? Having the `/var/log/azure/custom-script/handler.log` would also help.

**Comment by xpillons** [comment]
Sure, will do it Monday as I’ve tear down the machines now.

**Comment by xpillons** [comment]
Here is the content of the file 0-status and the handler.log files
[cid:image001.png@01D2180D.2E683B30]

Thanks,
Xavier

**Comment by ahmetalpbalkan** [comment]
@xpillons Please reply on GitHub.

**Comment by xpillons** [comment]
Here is the handler content

+ /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.1/bin/custom-script-extension install
time=2016-09-26T13:30:21Z version=v2.0.1/git@0f92134-clean operation=install seq=0 event=start
time=2016-09-26T13:30:21Z version=v2.0.1/git@0f92134-clean operation=install seq=0 status="not reported for operation (by design)"
time=2016-09-26T13:30:21Z version=v2.0.1/git@0f92134-clean operation=install seq=0 event="created data dir" path=/var/lib/waagent/custom-script
time=2016-09-26T13:30:21Z version=v2.0.1/git@0f92134-clean operation=install seq=0 event=installed
time=2016-09-26T13:30:21Z version=v2.0.1/git@0f92134-clean operation=install seq=0 status="not reported for operation (by design)"
time=2016-09-26T13:30:21Z version=v2.0.1/git@0f92134-clean operation=install seq=0 event=end
Writing status to /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.1/status/0.status.
+ nohup /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.1/bin/custom-script-extension enable
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event=start
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 message="checking for state migration"
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 message="no old state found to migrate"
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="reading configuration"
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="read configuration"
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="validating json schema"
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="json schema valid"
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="parsing configuration json"
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="parsed configuration json"
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="validating configuration logically"
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="validated configuration"
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="comparing seqnum" path=/var/lib/waagent/custom-script/seqnum
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="seqnum saved" path=/var/lib/waagent/custom-script/seqnum
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="creating output directory" path=/var/lib/waagent/custom-script/download/0
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="created output directory"
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 files=1
time=2016-09-26T13:30:26Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 file=0 event="download start"
time=2016-09-26T13:30:27Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 file=0 event="download complete" output=/var/lib/waagent/custom-script/download/0
time=2016-09-26T13:30:27Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="executing command" output=/var/lib/waagent/custom-script/download/0
time=2016-09-26T13:32:30Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="executed command" output=/var/lib/waagent/custom-script/download/0
time=2016-09-26T13:32:30Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event=enabled
time=2016-09-26T13:32:30Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event=end
Writing status to /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.1/status/0.status.
+ nohup /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.1/bin/custom-script-extension enable
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event=start
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 message="checking for state migration"
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 message="no old state found to migrate"
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="reading configuration"
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="read configuration"
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="validating json schema"
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="json schema valid"
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="parsing configuration json"
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="parsed configuration json"
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="validating configuration logically"
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="validated configuration"
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="comparing seqnum" path=/var/lib/waagent/custom-script/seqnum
time=2016-09-26T13:34:16Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event=exit message="this script configuration is already processed, will not run again"

status file content is no more available as I've stopped the VM, but it has message="Enable in progress"

**Comment by ahmetalpbalkan** [comment]
@xpillons do you have the command/template to reproduce this? I can't seem to repro it myself.

**Comment by xpillons** [comment]
@ahmetalpbalkan it is all here https://github.com/xpillons/azure-hpc/tree/master/Compute-Grid-Infra look at nodes-linux-resources.json which is called by deploy-nodes.json

**Comment by jjjordanmsft** [comment]
Why doesn't the new version show the stdout/stderr output in Resource Explorer anymore?  This was a vital debugging tool for us.  Logging into the machines is not always an option.

**Comment by ahmetalpbalkan** [comment]
@jjjordanmsft We'll get it implemented soon.

**Comment by ahmetalpbalkan** [comment]
(Internal note) It appears like the feature request here is to modify the status message to have an additional `\n---stdout---\n(tail of stdout file up to 4096 bytes)\n---errout--\n(tail of stderr file, up to 4096 bytes)`. It would look like this:

    "message": "Command returned an error.\n---stdout---\nReading package lists...\nBuilding dependency tree...\nReading state information...\n\n---errout---\nE: Unable to locate package htops\n\n",

This makes the behavior the same as Microsoft.OSTCExtensions.CustomScriptForLinux v1.x.

It's particularly unfortunate that users relied on this "undocumented feature" in their templates such as the one quoted above and [this one](https://github.com/Azure/azure-quickstart-templates/tree/master/vm-to-vm-throughput-meter-multithreaded) but it looks like an easy feature to implement. Some actually go very far to `split(message, '\n')[2]` to get the first line of the stdout from extension and produce Template Outputs with that. 😕 This is totally hacky and relies on nothing covered by any guarantees.

It's also unfortunate that it was called `---errout---` in the initial version. I see that it should be okay to replace this with `---stderr---` in the new version. I will take a look at implementing this soon.

**Comment by boumenot** [comment]
This was implemented in Feb 2017-ish.
