### ISSUE TITLE
The assumption about the file mode (500)

### ISSUE THREAD

**Issue by bingosummer** [Azure/custom-script-extension-linux#68]
It is assumed that users download scripts to execute. But in some cases, the files are downloaded for other reasons. For example, maybe we want to edit the files.

https://github.com/Azure/custom-script-extension-linux/blob/master/main/files.go#L32

**Comment by ahmetalpbalkan** [comment]
@bingosummer so far we have not heard any reports of people broken downstream by this. Also I think in this case we would rather break the users as we believe this is the right thing to do. Users should take a copy of the downloaded files and then modify them. Editing the original files will lose our ability to diagnose things when it goes wrong.

Is there a case where this does not work?

**Comment by bingosummer** [comment]
https://github.com/Azure/azure-quickstart-templates/blob/master/bosh-setup/scripts/setup_env#L109-L110

We copy the downloaded files to the home directory, and users will edit the file after CustomScript is done. So, I should `chmod 600` the copy of the downloaded files in the script to make it work.

Another question: From the assumption, I think, if the files are not to execute, it's not recommended to download them by `fileUris`. Instead, they should be downloaded using a `wget` command in the script. Is my understanding right?

**Comment by ahmetalpbalkan** [comment]
@bingosummer You can still use `fileUris` field to specify files to download. The extra +x bit is harmless and you can strip it off. If you use `fileUris` instead of using wget in user-script, you will be getting retries with exponential backoff for free.

**Comment by bingosummer** [comment]
Got it. Thanks.
