### ISSUE TITLE
Extension showing transitioning state after completes

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/custom-script-extension-linux#70]
We just discovered a bug that when a script execution completes and another `enable` call comes to `custom-script-shim enable`, we write a status saying "Transitioning" but since we processed the seqnum we immediately exit, without reporting the status.

If enable gets called twice in short successions, like a minute, the `.status` file with status like "Failed" or "Completed" gets overwritten and the portal/ARM engine thinks it's still "Transitioning".

The reason we write a "Transitioning" file before forking into background is because waagent checks for the `.status` file when the extension entrypoint returns. So this file serves as a placeholder.

The solution would be to not to overwrite the `{N}.status` file if it already exists in the `custom-script-shim`.

**Comment by ahmetalpbalkan** [comment]
Closed via #71. Will publish as `v2.0.2`.

**Comment by TimLovellSmith** [comment]
@ahmetb I am seeing a very similar issue with Windows VM custom script extensions. That is a separate repo though?

**Comment by davoodharun** [comment]
@TimLovellSmith I believe they are separate repositories. I am also experiencing the same issue with Windows VM custom script extension. It looks like my script executes and does what it needs to, but then eventually the extension times out and is stuck in transitioning

**Comment by nmb88** [comment]
@ahmetb, I'm seeing this still.  The operations in the custom script extension have completed but the status is still 'transitioning'.  The output in the .status file shows everything is completed but has the wrong status:

`[{"status":{"code":1,"formattedMessage":{"lang":"en-US","message":"Asynchronously executing the specified command"},"name":"SecureCommand_0","operation":"Executing Command","status":"transitioning","substatus":[{"code":0,"formattedMessage":{"lang":"en-US","message":"Success Restart Needed Exit Code      Feature Result                           \\n------- -------------- ---------      --------------                           \\nTrue    No             Success        {ASP.NET 4.6, .NET Framework 3.5 (incl...\\nnewrelic-infra.msi Installation successful!\\nNewRelicDotNetAgent_x64.msi Installation successful!\\nWARNING: It's very likely you will need to close and reopen your shell \\n  before you can use choco.\\nWARNING: You can safely ignore errors related to missing log files when \\n  upgrading from a version of Chocolatey less than 0.9.9. \\n  'Batch file could not be found' is also safe to ignore. \\n  'The system cannot find the file specified' - also safe.\\nPATH environment variable does not have C:\\ProgramData\\chocolatey\\bin in it. Adding...\\nWARNING: Not setting tab completion: Current user is SYSTEM user."},"name":"StdOut","status":"success"},{"code":0,"formattedMessage":{"lang":"en-US","message":""},"name":"StdErr","status":"success"}]},"timestampUTC":"\/Date(1499531828252)\/","version":"1"}]`
