### ISSUE TITLE
timestamp option

### ISSUE THREAD

**Issue by mschirrmeister** [Azure/custom-script-extension-linux#74]
Hello,

I was implementing the `timestamp` option in our templates. I do normally all values that can be changed as a parameter. So I did timestamp as parameter and specified it as `201610281004`. I liked a timestamp like YYMMDDhhmm.

I always got an error back.
```
error:   Unable to process template language expressions for resource '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/marco-vmtest-east-us-1/providers/Microsoft.Compute/virtualMachines/azeausmarcotest11/extensions/azureVmUtils' at line '1' and column '6559'. 'The template language function 'int' cannot convert provided value '201611011232' to integer value. Please see https://aka.ms/arm-template-expressions/#int for usage details.'
```

I was talking with support and we figured out, that the timestamp has some boundaries. I was told it is `[-2147483648, 2147483647]`.

Can the documentation be updated to reflect those limits?

Thanks
Marco

**Comment by ahmetalpbalkan** [comment]
Thanks for reporting @mschirrmeister!
