### ISSUE TITLE
Broken on Alpine: readlink behavior difference

### ISSUE THREAD

**Issue by ddebroy** [Azure/custom-script-extension-linux#76]
When trying to deploy a CustomScript extension, I am getting this error: "No such file or directory: '/var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.2/status/0.status'" when /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.2/bin/custom-script-shim is executed as part of enabling the extension. I was trying to debug this a little more and wanted to know who is supposed to create the status file that custom-script-shim @ https://github.com/Azure/custom-script-extension-linux/blob/master/misc/custom-script-shim#L24 is checking for (where the error is happening in my environment). Any pointers?

**Comment by ddebroy** [comment]
Turns out in the custom BusyBox env. I was trying to get this working on has a version of readlink that works differently from the standard version in say Ubuntu. The readlink -f command in custom-script-shim errors out in my environment when the file does not exist causing the enablement of custom script to fail.

**Comment by ahmetalpbalkan** [comment]
@ddebroy would you like to keep the issue open? Could you describe your env a bit more, are you using busybox as your VM image, or are you running your images in some container? Ideally `readlink -f` should fail when the file does not exist. If you could send the logs, perhaps we can assist better.

**Comment by ddebroy** [comment]
@ahmetalpbalkan yes I would like to keep the issue opened and see it fixed. The environment here is an Alpine Linux based container running busybox [https://hub.docker.com/r/docker4x/agent-azure/]. waagent runs fine for us in this environment but when trying to enable Custom Script extensions, we are running into the error:

```
2016/11/18 00:10:57.250564 ERROR Event: name=Microsoft.Azure.Extensions.CustomScript, op=Enable, message=(000003)Non-zero exit code: 1, bin/custom-script-shim enable
```

I have narrowed it down to the usage of readlink -f at https://github.com/Azure/custom-script-extension-linux/blob/master/misc/custom-script-shim#L24 

In Ubuntu the readlink against a non existent status file does not error out - it returns the path to a non existent file (which the code then checks if it actually exists). In the readlink version in busybox, readlink fails (for a file that does not already exist) and the set -ue option at the top of the script is causing custom-script-shim to bail out. If the script could be modified to not depend on readlink -f returning the canonical path to a non existent file, I think it should work even in the busybox environment.

**Comment by ahmetalpbalkan** [comment]
@ddebroy Understood. I believe waagent running in a container is not a supported scenario for us. However, patches are welcome. It appears like `status_file_path()` can just return without doing `readlink -f` and then we can evaluate it with readlink before using it at the "else" block of `write_status()`.

**Comment by ddebroy** [comment]
Sure. Are there any pointers on how we can deploy a test version of the extension script and configure waagent to pull it rather than the upstream/released version? When I submit the patch, I want to make sure it is doing the right things on our environment end2end as well as not breaking on standard distros.

**Comment by ahmetalpbalkan** [comment]
@ddebroy Unfortunately deployment can only be done for us. You can totally fake a new version by patching the downloaded package locally. To test your patch locally, I can recommend the following:

- install the extension to your VM: this will get the extension package delivered to your machine
- find `custom-script-shim` in `/var/lib/waagent/**` and patch it inside the container.
- delete state directory inside the container `/var/lib/waagent/custom-script`
- restart waagent (in this case, your container)
- observe `/var/log/waagent.log` to see the extension is enabled
- check `/var/log/azure/custom-script/handler.log` doesn't have the error anymore.

**Comment by ahmetalpbalkan** [comment]
@ddebroy do you have any updates here?

**Comment by ddebroy** [comment]
@ahmetalpbalkan I haven't had a chance to work on this last few days. If you want, you can close this issue for now and I can open a PR for this once I have some cycles.

**Comment by ahmetalpbalkan** [comment]
Great, thanks!
