### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by xplicit** [Azure/custom-script-extension-linux#77]
Please add to the documentation:

* List of extension options (i.e. `--public-config`)
* Which extension command to use to re-download and execute script file if the content of file is changed, without reinstalling extension again.
* How to get script output info (from client)

**Comment by ahmetalpbalkan** [comment]
@xplicit are you referring to `README.md` here as the documentation or the https://docs.microsoft.com/azure/virtual-machines/virtual-machines-linux-extensions-customscript ?

> List of extension options (i.e. --public-config)

this is documented in both places.

> 

> Which extension command to use to re-download and execute script file if the content of file is changed, without reinstalling extension again.

this is also documented in both places: `- timestamp (optional, integer) use this field only to trigger a rerun of the script by changing value of this field.`

> How to get script output info (from client)

This is a feature that's not implemented in the new version (v2.0) yet (see #67). It is present in the old extension (Microsoft.OSTCExtensions.CustomScriptForLinux v1.5) which is still a good option to use. We will be adding the feature here soon as well.

**Comment by xplicit** [comment]
@ahmetalpbalkan Maybe I am missing something, but I don't see where is the list of all available commandline options with their descriptions. I saw some examples of using them but not full list.   

About timestamp: from description I understood that the script is executed only when timestamp is changed. But what I need is always update and execute the script without reinstalling extension for every run. When I run `azure vm extension set myResourceGroup myVM CustomScript Microsoft.Azure.Extensions 2.0 --auto-upgrade-minor-version --public-config...` every time I've got a message:  

`Installing extension "CustomScript", VM: "myVM"` 

but I've already installed extension on the first run and reinstalling it for every run takes additional time to execute script. Is timestamp changes this behavior and does not reinstall extension for every run?

**Comment by ahmetalpbalkan** [comment]
> Maybe I am missing something, but I don't see where is the list of all available commandline options with their descriptions.

The command line is not specific to CustomScript extension; it is generic. What goes into `--public-config` is documented [in this section](https://github.com/Azure/custom-script-extension-linux#11-public-configuration).

> But what I need is always update and execute the script without reinstalling extension for every run.

We don't check the URLs periodically to find out if the script is updated and it should be executed. In your case, changing the timestamp field and using `azure vm extension set` again with the new timestamp will get your script executed again.

> but I've already installed extension on the first run and reinstalling it for every run takes additional time to execute script.

I think the `Installing extension` message is a bit misleading on our CLI. If the extension is already present on your VM, it is not downloaded again. We simply update its configuration and re-run it. You see a delay on the `azure vm extension set` call not because it is downloading anything, mostly because there are delays in the API itself and this is not meant to be a low-latency API.

**Comment by xplicit** [comment]
> The command line is not specific to CustomScript extension; it is generic. What goes into --public-config is documented in this section.

So do I correctly understand there are command line options (from [this](https://github.com/Azure/custom-script-extension-linux/blob/master/README.md) and [this](https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-extensions-customscript))

    --auto-upgrade-minor-version
    --public-config-path
    --private-config-path
    --public-config
    --private-config

And there are no other command-line options?

**Comment by ahmetalpbalkan** [comment]
There might, be. To learn that, please refer to CLI's own help by running:

    azure vm extension set --help

**Comment by xplicit** [comment]
Thanks, that is what I looked for. If there was a sentence in documentation "To see list of all available  command line options of the extension type `azure vm extension set --help`" it would be very helpful. Because at first dealing with the azure extension I don't know which command line options are implemented in it, which are not, which are generic for all extensions, which are specific to only current one.

**Comment by ahmetalpbalkan** [comment]
Your point is valid. I'm copying @neilpeterson and @squillace to kindly take a look at if there's a gap in our docs not clearly stating how users can get more help on the CLI commands.

I'll go ahead and close this issue as it's not related to CustomScript project.

**Comment by neilpeterson** [comment]
@ahmetalpbalkan @xplicit - thanks, I agree with the suggestion and will push a change through.
