### ISSUE TITLE
How to force a script to be rerun ?

### ISSUE THREAD

**Issue by xpillons** [Azure/custom-script-extension-linux#79]
I've a scenario in which I've a script that had failed because of a typo. How have this new script being downloaded again and rerun, considering I'm using an ARM template ?
Thanks

**Comment by ahmetalpbalkan** [comment]
@xpillons this is documented in README.md as the `timestamp` field. You need to just change something in the extension configuration (such as the value of `timestamp` field or add some spaces in your command) and redeploy your ARM template. It will be re-run.

**Comment by xpillons** [comment]
in fact if timestamp is not already there, adding it doesn't work.

**Comment by ahmetalpbalkan** [comment]
@xpillons you need to change its value as I described above?

**Comment by xpillons** [comment]
That is the point. If timestamp is not present when you first deploy, adding it afterwards won’t trigger the script to be rerun.

**Comment by ahmetalpbalkan** [comment]
It should be executing again when you add a field as well. Can you please share the logs (see README.md) if you see this behavior?

**Comment by srinu259** [comment]
I am able to re-run the script by adding the timestamp. When I first deployed, I didnt had the timestamp and for some reasons script execution failed, so I was able to re-run it by adding the timestamp.
