### ISSUE TITLE
stdout and stderr not returned

### ISSUE THREAD

**Issue by joerage** [Azure/custom-script-extension-linux#81]
I am running a template which executes the following script:

```
#!/bin/bash
echo 'This is good'
>&2 echo "This is no good"
exit 1
```

I was expecting the status message of the extension result to contain the two stdout and stderr outputs. But it does not. It only has:
```
Enable failed: failed to execute command: command terminated with exit status=1
```

How can I see (without login in the machine) the outputs of my extension deployment?

**Comment by ahmetalpbalkan** [comment]
This feature is implemented with patch #78 however it is not released for use yet. We are planning to release it soon.

**Comment by dovreshef** [comment]
What's the status of this feature? I can see that the PR is merged, but the latest version on Azure (2.0.2) does not have this. Is there an ETA?

Thanks,

**Comment by boumenot** [comment]
The status of this feature is that it needs to be restarted.  The champion of this work has left the company, and we need to find a new champion.  We hope to resolve that soon.

In the interim I've released a *beta* version that uses the code in master.  The extension has been published to **southcentralus** under the namespace Microsoft.Azure.Extensions.**Edp**.  I have not verified this version yet, but if you like to provide feedback it would be appreciated.  This version can be used by

 1. Targetting a deployment to southcentralus.
 1. Changing the namespace from Microsoft.Azure.Extensions to Microsoft.Azure.Extensions.Edp

**Comment by boumenot** [comment]
I have release 2.0.3 to address this issue.  It should be available now or imminently.  Please let me know if this works for you or not.

**Comment by s1rc0** [comment]
Hey @boumenot 
so, I understand correctly, now I can print  a output stdout/stderr when I do deploy via "az group deployment create ...... " ?

**Comment by boumenot** [comment]
stdout/stderr are now captured, and displayed in the portal as was done with the older version of CustomScript.  Does that answer your question?

**Comment by s1rc0** [comment]
Yes, Many Thanks!
