### ISSUE TITLE
storageAccountKey from key vault fails regex validation

### ISSUE THREAD

**Issue by gabe19** [Azure/custom-script-extension-linux#83]
I have a custom script agent which pulls down a blob file from azure storage for execution. Everything goes well if the account key is provided as a parameter or entered directly into the extension template text, but fails a regex when the parameter references a key vault entry in the parameters template.  The key vault based parameter value comes through if I output it in the output section of the template. I cannot tell from the logs what value is being evaluated on the server when the extension attempts download.

Would this capability be expected to work?

Template section:
```json
{
      "name": "[concat(variables('proxyMachineName'),'/CustomScriptForLinux')]",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "[resourceGroup().location]",
      "apiVersion": "2015-06-15",
      "tags": {
        "department": "Engineering"
      },
      "properties": {
        "publisher": "Microsoft.Azure.Extensions",
        "type": "CustomScript",
        "typeHandlerVersion": "2.0",
        "autoUpgradeMinorVersion": true,
        "settings": {
          "fileUris": [
            "https://automatedata001.blob.core.windows.net/deployment-scripts/install-proxy.sh"
          ]
        },
        "protectedSettings": {
          "commandToExecute": "sudo sh ./install-proxy.sh",
          "storageAccountName": "automatedata001",
          "storageAccountKey": "[parameters('DeploymentFileDiskAccessKey')]"
        }
      },
      "dependsOn": [
        "[concat('Microsoft.Compute/virtualMachines/', variables('proxyMachineName'),'/extensions/DockerExtension')]"
      ]
    }
```
Logs:

[CommandExecution.log.txt](https://github.com/Azure/custom-script-extension-linux/files/655435/CommandExecution.log.txt)

[handler.log.txt](https://github.com/Azure/custom-script-extension-linux/files/655431/handler.log.txt)
[waagent.log.txt](https://github.com/Azure/custom-script-extension-linux/files/655447/waagent.log.txt)

**Comment by boumenot** [comment]
I changed your comment slightly to make the template JSON easier to read.

The protected settings is a JSON document that the extension parses, and it validates the schema using this [code](../blob/master/main/schema.go).  The code expects the storage key to be base64 encoded value, but I *think* you are saying this is actually a KeyVault URL, correct?

If so, the code does not currently support a KeyVault URL.  It makes sense that it should.

**Comment by gabe19** [comment]
Thanks Christopher, I'll try to improve my markdown skills in this comment.  The reference in the template is actually to a parameter which is being provided by a key vault reference.  In my parameters json I have:

```json
 "DeploymentFileDiskAccessKey": {
      "reference": {
        "keyVault": {
          "id": "/subscriptions/[mysubscriptionguid]/resourceGroups/[myresourcegroupname]/providers/Microsoft.KeyVault/vaults/myvaultname"
        },
        "secretName": "SecretName"
      }
    }
```
Where the "SecretName" is the name of the base64 encoded value which is stored in the vault and which I wish to pass. This is a valid value if I use it directly without using the key vault. If I output the parameter value from the template, it is available but I suspect that perhaps it isn't being decoded prior to use in the script?

**Comment by colemickens** [comment]
Is the secret value supposed to be base64 encoded? Though I wouldn't rule out a documentation gap, [the KeyVault REST docs don't say anything about needing to base64 encode Secret values in KeyVault](https://docs.microsoft.com/en-us/rest/api/keyvault/setsecret) (and of course there are no examples of the KeyVault-Secret-Template scenario that doesn't use the Portal or Visual Studio, so it's hard to confirm recommended usage).

I know you need to do the "base64 a JSON blob" for certs you wanted deployed to a Compute VM, but maybe give a this template parameter value scenario a try with a non-base64 encoded secret?

**Comment by boumenot** [comment]
Closing due to lack of response.
