### ISSUE TITLE
Additional Install Event Logging

### ISSUE THREAD

**Issue by danielsollondon** [Azure/custom-script-extension-linux#87]
Can you add a clear event that Installation Succeeded and Failed, then any failure after that will imply that it is a command/script error, For install failed, please can you use Error Code 52 : “Installation Failed”.

**Comment by boumenot** [comment]
The agent logs an event when install occurs.  It looks like

```text
Launch command succeeded: bin/custom-script-shim install
```

The event will be marked as failed.

The failures I am seeing for custom-script appear to be in the bash script that acts as a shim.  This is also a point of contention for other customers (see issues).
