### ISSUE TITLE
Command not being executed

### ISSUE THREAD

**Issue by a8ree** [Azure/custom-script-extension-linux#88]
Hi,

I am running the following code however it isn't being executed. I get the following success message

RequestId IsSuccessStatusCode StatusCode ReasonPhrase
--------- ------------------- ---------- ------------
                         True         OK OK 

But the handler.log isn't showing anything

```
$RGName = "cybersecurity"
$VmName = "KaliX001"
$Location = "West Europe"

$ExtensionName = 'CustomScript'
$Publisher = 'Microsoft.Azure.Extensions'
$Version = '2.0'

$PublicConf = '{
    "fileUris": ["https://kalideploy.blob.core.windows.net/scripts/updatevm.sh2"],
    "commandToExecute": "updatevm.sh2"
}'

Set-AzureRmVMExtension -ResourceGroupName $RGName -VMName $VmName -Location $Location -Name $ExtensionName -Publisher $Publisher -ExtensionType $ExtensionName -TypeHandlerVersion $Version 
```

**Comment by boumenot** [comment]
Can you please attach logs so we can debug this further.

/var/log/waagent.log
/var/log/azure/Microsoft.Azure.Extensions.CustomScript/*
/var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/*

It looks like you are running on a Kali VM, which is not officially supported.  If so....  This mostly means we do not execute test cases against these VM, nor do we validate versions on them.  There may be issues that break us that we are not aware of.  I am happy to look, but I may not be able to provide a fix.

**Comment by boumenot** [comment]
Closing due to lack of response.
