### ISSUE TITLE
Issue downloading binary file

### ISSUE THREAD

**Issue by gregjhogan** [Azure/custom-script-extension-linux#92]
I am attempting to pull down the OMS dependency agent from a storage account, and I get the following error:

STDOUT
```
Dependency Agent 9.0.5.737 Setup for Linux
==========================================================================

Checking installation environment...
No old version of the Dependency Agent found.  Performing fresh installation.
Using default base directory of / for silent installation.
```

STDERR
```
Extraction of dependency-agent.x86_64.rpm failed.  Installer may be corrupt.

The Dependency Agent was not installed.
```

TEMPLATE
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "2.0.0",
    "parameters": {
        "vm": {
            "type": "string",
            "metadata": {
                "description": "name of a virtual machine"
            }
        },
        "location": {
            "type": "string",
            "defaultValue": "[resourceGroup().location]",
            "metadata": {
                "description": "location of the resource"
            }
        }
    },
    "variables": {
        "apiVersion": "2015-06-15",
        "baseUri": "[concat(split(deployment().properties.templateLink.uri, '/templates/')[0], '/')]",
        "sasToken": "[concat('?',split(deployment().properties.templateLink.uri,'?')[1])]"
    },
    "resources": [
        {
            "apiVersion": "[variables('apiVersion')]",
            "type": "Microsoft.Compute/virtualMachines/extensions",
            "name": "[concat(parameters('vm'),'/agents')]",
            "location": "[parameters('location')]",
            "tags": {
                "template": "[concat(split(split(deployment().properties.templateLink.uri,'/')[5],'.')[0],'@',split(deployment().properties.templateLink.uri,'/')[4])]"
            },
            "properties": {
                "publisher": "Microsoft.Azure.Extensions",
                "type": "CustomScript",
                "typeHandlerVersion": "2.0",
                "settings": {
                    "fileUris": [
                        "[concat(variables('baseUri'), 'agents/InstallDependencyAgent-Linux64.bin', variables('sasToken'))]"
                    ],
                    "commandToExecute": "sh InstallDependencyAgent-Linux64.bin -s"
                },
                "protectedsettings": { }
            }
        }
    ]
}
```

If I pull down the same file inside the VM using `curl` I can see that the line feeds have been converted, so I am guessing the issue is it is downloading the file in text mode.

![image](https://cloud.githubusercontent.com/assets/4112046/25768268/309e0b6c-31c7-11e7-9696-5c1f19755592.png)

**Comment by boumenot** [comment]
Apologies for replying so late.

You are correct that the file was modified, but this isn't related to download.  CustomScript has explicit support for dos2unix conversion because many customers were editing scripts on Windows and then running them on Linux.  This functionality existed in the previous version as was carried forward.  The code tries to determine if the script being executed is a text file based on common file extensions or by checking for the shebang.  I can't see your whole script, but my guess is it has a shebang at the top.

You can try removing the shebang and re-running.  I can also consider adding an override to skip conversion.

**Comment by gregjhogan** [comment]
@boumenot it is the OMS dependency agent, so I can't really change it.  It is a script that has a bunch of raw binary data at the end.  It is actually both a script and binary data all in one file!

While I can understand this being the default behavior, can you add an option to force binary mode?

**Comment by boumenot** [comment]
I can, and that's what I meant by skipping conversion.  My other suggestion is to simply change your custom script commandToExecute to download the script using wget and then execute it.

```sh
wget http://... -o my.sh && sh ./my.sh
```

**Comment by gregjhogan** [comment]
@boumenot yeah, that is pretty much what I did to work around the issue:
```
          "commandToExecute": "[concat('curl -s ''', variables('baseUri'), 'agents/InstallDependencyAgent-Linux64.bin', variables('sasToken'), ''' -o InstallDependencyAgent-Linux64.bin && sh InstallDependencyAgent-Linux64.bin -s --force')]"
```

**Comment by boumenot** [comment]
v2.0.4 exposes a flag to control auto conversion from dos2unix.
