### ISSUE TITLE
v2.0.3 - didn't follow Waagent's lib-dir setting and always download to "/var/lib/waagent"

### ISSUE THREAD

**Issue by u6006** [Azure/custom-script-extension-linux#93]
Our Waagent has its lib-dir set to a different directory from "/var/log/waagent". However Custom Script v2.0.3 uses the hardcoded "/var/lib/waagent/" to store the downloaded script(s).

The other issue is our "/var/" has no execution permission, as such we have to run the provided script in the format of "bash a.sh" rather than "a.sh".
To be more important, it breaks our policy: no execution permission for "/var/".

IMO, this is the bug that MUST be fixed.

**Comment by boumenot** [comment]
I am not aware of any endorsed distro that uses anything besides /var/lib/waagent.  What distro is this issue against?

Feel free to send a PR.

**Comment by u6006** [comment]
IMO, the Linux flavor has nothing to do with this bug. The issue is the extension didn't follow the the "Lib.Dir" setting in "waagent.conf", instead it uses the hardcoded "/var/lib/waagent/".

In my case, the extension itself was downloaded and installed to the changed Waagent "Lib.Dir", but the downloaded script is in "/var/lib/waagent/" where the execution permission was revoked.

**Comment by boumenot** [comment]
You're correct, the code is wrong.  There has also never been an instance where this assumption has been violated for an endorsed distro, which isn't intended to be an excuse, but is my assumption as to why it was written that way.  I am happy to review a PR to address this change.

**Comment by u6006** [comment]
I'd love to send out a PR to address this issue. However, there're issues after checking the code:

1. the framework is missing to parse the traditional .conf file with Go (I have no idea about Go, but it sounds like the configs are preferred to be saved in .json files)
2. it would be better if there're existing Azure Extensions that honor the Waagent settings and they're written in Go
2.1 it would be much better if there's the high-level design existing to deal with this kind of issues in Azure Extensions

**Comment by boumenot** [comment]
There are no plans to change the behavior at this time.  PRs are always welcome.
