### ISSUE TITLE
Running extension multiple times

### ISSUE THREAD

**Issue by hansenms** [Azure/custom-script-extension-linux#94]
I have a scenario, where I would like to be able to add the script extension multiple times:

I have one deployment that I use to generate a managed disk image that will later be used with a VM Scale Set. I have a script that sets up the image and when I create the image, I would like to run that script using the custom script extension. When the image is then used with the VM Scale Set, I would also like to add a custom script to configure a few things when the VMs start, but the script doesn't run because the custom script extension was used to create the image (there is some stuff in /var/lib/waagent). In order to make it work, I have to run `az vm extension delete ...` before de-provisioning and capturing the image. It would be nice if the extension would run even if it has run before.

**Comment by boumenot** [comment]
Are you using the timestamp field to re-trigger custom script in the case where the configuration is the same?  (I cannot tell if this is applicable in your case or not?)

Have you considered using Packer to create your image, or are you barred from doing that because you want to use a managed disk?

**Comment by hansenms** [comment]
The configuration is not the same. It is a different script that I run when I set up the image and when I deploy it, so my expectation was that it would work, but it doesn't. 

I don't know Packer, can you tell me more?

**Comment by boumenot** [comment]
I would expect it to work too. Would you please send logs so I can try to diagnose the issue.

- /var/log/azure/custom-script/handler.log
- /var/log/waagent.log

For information on Packer see: https://www.packer.io/.  Documentation for the Azure builder can be found here: https://www.packer.io/docs/builders/azure.html.

If you want to jump right in, check out the examples.  The fastest way to get up and running is with the [Ubuntu quick start example](https://github.com/hashicorp/packer/blob/master/examples/azure/ubuntu_quickstart.json).

**Comment by hansenms** [comment]
Files attached. 

The log pretty much says it:

```
Not writing a placeholder status file, already exists: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/status/0.status
+ nohup /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/bin/custom-script-extension enable
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=start
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=pre-check
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="checking for state migration"
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="no old state found to migrate"
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="comparing seqnum" path=/var/lib/waagent/custom-script/seqnum
time=2017-05-09T17:44:08Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=exit message="this script configuration is already processed, will not run again"
```
Just not sure why it says it has already run. It is a different script, with different files.  The first time it runs is in this file: 

https://github.com/hansenms/azure_templates/blob/master/image_generator.json#L215 

The machine is then deprovisioned, captured and then used in this one:

https://github.com/hansenms/azure_templates/blob/master/gadgetron.json#L281

So the script is different, the deployment is different, the group is different, the name of the extension is different. Still, it doesn't run. 

Thoughts?

PS. I will look at Packer, but I was really trying to make it just run all in Azure with the basic tools and not have to install yet another tool. I have some shell scripts that do all of this, just trying to make them simpler. 

[handler.log.txt](https://github.com/Azure/custom-script-extension-linux/files/987571/handler.log.txt)
[waagent.log.txt](https://github.com/Azure/custom-script-extension-linux/files/987572/waagent.log.txt)

**Comment by boumenot** [comment]
My thoughts are that deprovision is not deleting enough stuff from the VM, and as a result it is breaking CustomScript.  Can you verify that this directory still exists after a deprovision?  If so, please delete it and retry.  If this is the issue, I will follow up with the agent team.

There is no need to preserve this directory across rebuilds, so just 

```sh
rm -rf /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript*/
```

What is the full deprovision command with options that you ran?

I hear you.  I don't mean to pile on yet another tool for you, but this is our recommended way for creating VM images.  I see no reason you cannot be successful with this method.

**Comment by hansenms** [comment]
Yes, that folder is there and the `az vm extension delete ...` does delete it and after that it works. The deprovisioning command is `sudo waagent -force -deprovision`. It is not really a major deal to have to delete the extension, it is just not intuitive that you have to delete it. Or if you get an image from somewhere that somebody created but didn't delete the extension before making the image, you cannot put the extension on. I think it is probably more of a bug than a feature, but I may well be misunderstanding the reason for the behavior.

**Comment by boumenot** [comment]
Thank you for the confirmation.  I'll follow up with the agent team on this.  The docs for deprovision do not call out that extension data are cleaned up, but they should be IMHO.  I am closing this issue, and I will follow up with them in another issue against their repository.

**Comment by hansenms** [comment]
Great, thanks!

**Comment by boumenot** [comment]
Circling back.., The agent team closed the issue because the guest agent version 2.1+ will delete these data.  From the logs you are running an older version, WALinuxAgent-2.0.16.  Based on the kernel version, I guess that you are running Ubuntu 14.04.  The latest version of the agent are in the newer Ubuntu 14.04 gallery images, so it would be worthwhile to snap to a later version if possible.

**Comment by hansenms** [comment]
Thanks for the tip. It was on my to do list to update our images to 16.04, so I have just set that in motion. If that solves it, that would be great.
