### ISSUE TITLE
HOME is unset and a docker issue

### ISSUE THREAD

**Issue by phahulin** [Azure/custom-script-extension-linux#97]
Hello,

trying to use this extension on Ubuntu 16.04 vm to install a few services. I download and run a `.sh` script by specifying it in `properties.settings.fileUris`. Here are some problems I got, any help will be greatly appreciated!

1. if I print `$HOME` env. variable it appears that it's unset, though `whoami` correctly returns `root`, is this desired behaviour?
2. I also try to install docker and follow [post installation steps](https://docs.docker.com/engine/installation/linux/linux-postinstall/) to run it under non-root user. On step3 it requires to "Log out and log back in", which I can't do during installation. I've googled that running `newgrp docker` should help and indeed it does, if I run it manually. However if running via script, it doesn't work, new group is not added (I check via `groups`).

**Comment by boumenot** [comment]
1. This is distro specific.  The extension is invoked by the agent, which may not have a home directory set.  This is expected.
1. Sorry, I do not know how to solve this using Custom Script nor is this a specific issue with Custom Script.
